/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author acer
 */
public class Dashbord extends javax.swing.JFrame {

    /**
     * Creates new form dashbord
     */
    public Dashbord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        invoice = new javax.swing.JLabel();
        Accesaries1 = new javax.swing.JLabel();
        customer1 = new javax.swing.JLabel();
        supplier1 = new javax.swing.JLabel();
        panal2 = new javax.swing.JPanel();
        custdet = new javax.swing.JLabel();
        addcust = new javax.swing.JLabel();
        panal5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panal6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panal7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panal4 = new javax.swing.JPanel();
        invdet = new javax.swing.JLabel();
        addinv = new javax.swing.JLabel();
        panal3 = new javax.swing.JPanel();
        addsup = new javax.swing.JLabel();
        supdet = new javax.swing.JLabel();
        panal8 = new javax.swing.JPanel();
        accdet = new javax.swing.JLabel();
        addacc = new javax.swing.JLabel();
        panal9 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        panal10 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        panal11 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 625));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Customer Count");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setText("00000");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 80, 30));

        jPanel11.setBackground(new java.awt.Color(255, 153, 153));

        jLabel31.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel31.setText("Customer");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addContainerGap())
        );

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 50));

        jPanel5.setBackground(new java.awt.Color(0, 204, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Accesaries Count");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setText("00000");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 80, 30));

        jPanel6.setBackground(new java.awt.Color(51, 255, 102));

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel11.setText("Accesaries");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 50));

        jPanel7.setBackground(new java.awt.Color(204, 153, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("Supplier Count");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText("00000");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 80, 30));

        jPanel8.setBackground(new java.awt.Color(255, 255, 102));

        jLabel20.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel20.setText("Supplier");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addContainerGap())
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 50));

        jPanel9.setBackground(new java.awt.Color(0, 204, 204));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setText("Invoice Count");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabel28.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel28.setText("00000");
        jPanel9.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, 30));

        jPanel10.setBackground(new java.awt.Color(102, 255, 204));

        jLabel29.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel29.setText("Invoice");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addContainerGap())
        );

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 50));

        jLabel30.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel30.setText("Dashbored");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel30)
                .addGap(67, 67, 67)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 900, 700));

        invoice.setFont(new java.awt.Font("Segoe UI Emoji", 1, 25)); // NOI18N
        invoice.setText("Invoice");
        invoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                invoiceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                invoiceMouseExited(evt);
            }
        });
        jPanel1.add(invoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 110, 30));

        Accesaries1.setBackground(new java.awt.Color(255, 102, 0));
        Accesaries1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 25)); // NOI18N
        Accesaries1.setText("Accesaries");
        Accesaries1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Accesaries1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Accesaries1MouseExited(evt);
            }
        });
        jPanel1.add(Accesaries1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 140, 30));

        customer1.setBackground(new java.awt.Color(0, 0, 0));
        customer1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 25)); // NOI18N
        customer1.setText("Customer");
        customer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customer1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customer1MouseExited(evt);
            }
        });
        jPanel1.add(customer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 130, 30));

        supplier1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 25)); // NOI18N
        supplier1.setText("Supplier");
        supplier1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplier1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplier1MouseExited(evt);
            }
        });
        jPanel1.add(supplier1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 110, 30));

        panal2.setBackground(new java.awt.Color(255, 153, 0));
        panal2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panal2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panal2MouseExited(evt);
            }
        });
        panal2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        custdet.setFont(new java.awt.Font("Yu Gothic Medium", 1, 17)); // NOI18N
        custdet.setForeground(new java.awt.Color(255, 255, 255));
        custdet.setText("Customer Detail");
        custdet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        custdet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                custdetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                custdetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                custdetMouseExited(evt);
            }
        });
        panal2.add(custdet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, -1));

        addcust.setFont(new java.awt.Font("Yu Gothic Medium", 1, 17)); // NOI18N
        addcust.setForeground(new java.awt.Color(255, 255, 255));
        addcust.setText("Add custumor");
        addcust.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addcust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addcustMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addcustMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addcustMouseExited(evt);
            }
        });
        panal2.add(addcust, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, -1));

        panal5.setBackground(new java.awt.Color(0, 102, 102));
        panal5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panal5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panal5MouseExited(evt);
            }
        });
        panal5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Yu Gothic Medium", 1, 17)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Customer Detail");
        panal5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, -1));

        jLabel15.setFont(new java.awt.Font("Yu Gothic Medium", 1, 17)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Add custumor");
        panal5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, -1));

        panal2.add(panal5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 180, 100));

        panal6.setBackground(new java.awt.Color(0, 102, 102));
        panal6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panal6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panal6MouseExited(evt);
            }
        });
        panal6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Yu Gothic Medium", 1, 17)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Customer Detail");
        panal6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, -1));

        jLabel17.setFont(new java.awt.Font("Yu Gothic Medium", 1, 17)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Add custumor");
        panal6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, -1));

        panal7.setBackground(new java.awt.Color(0, 102, 102));
        panal7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panal7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panal7MouseExited(evt);
            }
        });
        panal7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Yu Gothic Medium", 1, 17)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Customer Detail");
        panal7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, -1));

        jLabel19.setFont(new java.awt.Font("Yu Gothic Medium", 1, 17)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Add custumor");
        panal7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, -1));

        panal6.add(panal7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 180, 100));

        panal2.add(panal6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 180, 100));

        jPanel1.add(panal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 150, 90));

        panal4.setBackground(new java.awt.Color(255, 153, 0));
        panal4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panal4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panal4MouseExited(evt);
            }
        });
        panal4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        invdet.setFont(new java.awt.Font("Yu Gothic Medium", 1, 17)); // NOI18N
        invdet.setForeground(new java.awt.Color(255, 255, 255));
        invdet.setText("Invoice Detail");
        invdet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        invdet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invdetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                invdetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                invdetMouseExited(evt);
            }
        });
        panal4.add(invdet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, -1));

        addinv.setFont(new java.awt.Font("Yu Gothic Medium", 1, 17)); // NOI18N
        addinv.setForeground(new java.awt.Color(255, 255, 255));
        addinv.setText("Add Invoice");
        addinv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addinv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addinvMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addinvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addinvMouseExited(evt);
            }
        });
        panal4.add(addinv, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, -1));

        jPanel1.add(panal4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 140, 80));

        panal3.setBackground(new java.awt.Color(255, 153, 0));
        panal3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panal3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panal3MouseExited(evt);
            }
        });
        panal3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addsup.setFont(new java.awt.Font("Yu Gothic Medium", 1, 17)); // NOI18N
        addsup.setForeground(new java.awt.Color(255, 255, 255));
        addsup.setText("Add Supplier");
        addsup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addsup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addsupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addsupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addsupMouseExited(evt);
            }
        });
        panal3.add(addsup, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 10, 120, -1));

        supdet.setFont(new java.awt.Font("Yu Gothic Medium", 1, 17)); // NOI18N
        supdet.setForeground(new java.awt.Color(255, 255, 255));
        supdet.setText(" Supplier Detail");
        supdet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        supdet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supdetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supdetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supdetMouseExited(evt);
            }
        });
        panal3.add(supdet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 160, 40));

        jPanel1.add(panal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 170, 90));

        panal8.setBackground(new java.awt.Color(255, 153, 0));
        panal8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panal8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panal8MouseExited(evt);
            }
        });
        panal8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accdet.setFont(new java.awt.Font("Yu Gothic Medium", 1, 17)); // NOI18N
        accdet.setForeground(new java.awt.Color(255, 255, 255));
        accdet.setText("Accesaries Detail");
        accdet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accdet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accdetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accdetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accdetMouseExited(evt);
            }
        });
        panal8.add(accdet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 160, -1));

        addacc.setFont(new java.awt.Font("Yu Gothic Medium", 1, 17)); // NOI18N
        addacc.setForeground(new java.awt.Color(255, 255, 255));
        addacc.setText("Add Accesaries");
        addacc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addaccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addaccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addaccMouseExited(evt);
            }
        });
        panal8.add(addacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, -1));

        panal9.setBackground(new java.awt.Color(0, 102, 102));
        panal9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panal9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panal9MouseExited(evt);
            }
        });
        panal9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Yu Gothic Medium", 1, 17)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Customer Detail");
        panal9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, -1));

        jLabel23.setFont(new java.awt.Font("Yu Gothic Medium", 1, 17)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Add custumor");
        panal9.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, -1));

        panal8.add(panal9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 180, 100));

        panal10.setBackground(new java.awt.Color(0, 102, 102));
        panal10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panal10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panal10MouseExited(evt);
            }
        });
        panal10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Yu Gothic Medium", 1, 17)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Customer Detail");
        panal10.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, -1));

        jLabel25.setFont(new java.awt.Font("Yu Gothic Medium", 1, 17)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Add custumor");
        panal10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, -1));

        panal11.setBackground(new java.awt.Color(0, 102, 102));
        panal11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panal11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panal11MouseExited(evt);
            }
        });
        panal11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Yu Gothic Medium", 1, 17)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Customer Detail");
        panal11.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, -1));

        jLabel27.setFont(new java.awt.Font("Yu Gothic Medium", 1, 17)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Add custumor");
        panal11.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, -1));

        panal10.add(panal11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 180, 100));

        panal8.add(panal10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 180, 100));

        jPanel1.add(panal8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 150, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-supplier.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/invoice.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cust.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/accesaries.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Dashbord image.png"))); // NOI18N
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void invoiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_invoiceMouseEntered

    private void invoiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_invoiceMouseExited

    private void Accesaries1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Accesaries1MouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Accesaries1MouseEntered

    private void Accesaries1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Accesaries1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Accesaries1MouseExited

    private void customer1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer1MouseEntered
      
    }//GEN-LAST:event_customer1MouseEntered

    private void customer1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer1MouseExited
      
    }//GEN-LAST:event_customer1MouseExited

    private void panal3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panal3MouseEntered
     
    }//GEN-LAST:event_panal3MouseEntered

    private void panal3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panal3MouseExited
        
    }//GEN-LAST:event_panal3MouseExited

    private void supplier1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier1MouseEntered
       

    }//GEN-LAST:event_supplier1MouseEntered

    private void supplier1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier1MouseExited
    }//GEN-LAST:event_supplier1MouseExited

    private void panal2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panal2MouseEntered
        

    }//GEN-LAST:event_panal2MouseEntered

    private void panal2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panal2MouseExited
       
    }//GEN-LAST:event_panal2MouseExited

    private void panal4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panal4MouseEntered
      
    }//GEN-LAST:event_panal4MouseEntered

    private void panal4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panal4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panal4MouseExited

    private void panal5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panal5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panal5MouseEntered

    private void panal5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panal5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panal5MouseExited

    private void panal7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panal7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panal7MouseEntered

    private void panal7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panal7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panal7MouseExited

    private void panal6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panal6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panal6MouseEntered

    private void panal6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panal6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panal6MouseExited

    private void panal9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panal9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panal9MouseEntered

    private void panal9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panal9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panal9MouseExited

    private void panal11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panal11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panal11MouseEntered

    private void panal11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panal11MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panal11MouseExited

    private void panal10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panal10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panal10MouseEntered

    private void panal10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panal10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panal10MouseExited

    private void panal8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panal8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panal8MouseEntered

    private void panal8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panal8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panal8MouseExited

    private void addaccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addaccMouseEntered
       addacc.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_addaccMouseEntered

    private void addaccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addaccMouseExited
       addacc.setForeground(new Color(255,250,250));
    }//GEN-LAST:event_addaccMouseExited

    private void accdetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accdetMouseEntered
        // TODO add your handling code here:
          accdet.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_accdetMouseEntered

    private void accdetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accdetMouseExited
        // TODO add your handling code here:
         accdet.setForeground(new Color(255,250,250));
    }//GEN-LAST:event_accdetMouseExited

    private void addcustMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addcustMouseEntered
        // TODO add your handling code here:
         addcust.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_addcustMouseEntered

    private void addcustMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addcustMouseExited
         addcust.setForeground(new Color(255,250,250));
    }//GEN-LAST:event_addcustMouseExited

    private void custdetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custdetMouseEntered
        custdet.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_custdetMouseEntered

    private void custdetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custdetMouseExited
         custdet.setForeground(new Color(255,250,250));
    }//GEN-LAST:event_custdetMouseExited

    private void addsupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addsupMouseEntered
          addsup.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_addsupMouseEntered

    private void addsupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addsupMouseExited
         addsup.setForeground(new Color(255,250,250));
    }//GEN-LAST:event_addsupMouseExited

    private void supdetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supdetMouseEntered
          supdet.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_supdetMouseEntered

    private void supdetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supdetMouseExited
          supdet.setForeground(new Color(255,250,250));
    }//GEN-LAST:event_supdetMouseExited

    private void addinvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addinvMouseEntered
        addinv.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_addinvMouseEntered

    private void addinvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addinvMouseExited
         addinv.setForeground(new Color(255,250,250));
    }//GEN-LAST:event_addinvMouseExited

    private void invdetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invdetMouseEntered
          invdet.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_invdetMouseEntered

    private void invdetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invdetMouseExited
          invdet.setForeground(new Color(255,250,250));
    }//GEN-LAST:event_invdetMouseExited

    private void addaccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addaccMouseClicked
        try {
            AddAcceseries obj = new AddAcceseries();
            this.hide();
            obj.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Dashbord.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addaccMouseClicked

    private void addcustMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addcustMouseClicked
        Addcustomer cu = new Addcustomer();
        this.hide();
        cu.setVisible(true);
    }//GEN-LAST:event_addcustMouseClicked

    private void addsupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addsupMouseClicked
        AddSupplier ac = new AddSupplier();
        this.hide();
        ac.setVisible(true);
    }//GEN-LAST:event_addsupMouseClicked

    private void custdetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custdetMouseClicked
        Customerdetails cu = new Customerdetails();
        this.hide();
        cu.setVisible(true);
    }//GEN-LAST:event_custdetMouseClicked

    private void supdetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supdetMouseClicked
        SupplierDetails cu = new SupplierDetails();
        this.hide();
        cu.setVisible(true);
    }//GEN-LAST:event_supdetMouseClicked

    private void addinvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addinvMouseClicked
        Invoice cu = new Invoice();
        this.hide();
        cu.setVisible(true);
    }//GEN-LAST:event_addinvMouseClicked

    private void invdetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invdetMouseClicked
        InvoiceDetail cu = new InvoiceDetail();
        this.hide();
        cu.setVisible(true);
    }//GEN-LAST:event_invdetMouseClicked

    private void accdetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accdetMouseClicked
        AccessoriesDetails cu = new AccessoriesDetails();
        this.hide();
        cu.setVisible(true);
    }//GEN-LAST:event_accdetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashbord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Accesaries1;
    private javax.swing.JLabel accdet;
    private javax.swing.JLabel addacc;
    private javax.swing.JLabel addcust;
    private javax.swing.JLabel addinv;
    private javax.swing.JLabel addsup;
    private javax.swing.JLabel custdet;
    private javax.swing.JLabel customer1;
    private javax.swing.JLabel invdet;
    private javax.swing.JLabel invoice;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel panal10;
    private javax.swing.JPanel panal11;
    private javax.swing.JPanel panal2;
    private javax.swing.JPanel panal3;
    private javax.swing.JPanel panal4;
    private javax.swing.JPanel panal5;
    private javax.swing.JPanel panal6;
    private javax.swing.JPanel panal7;
    private javax.swing.JPanel panal8;
    private javax.swing.JPanel panal9;
    private javax.swing.JLabel supdet;
    private javax.swing.JLabel supplier1;
    // End of variables declaration//GEN-END:variables
}
